obstacle_range: 2.0
raytrace_range: 2.5
footprint: [[0.15, 0.25], [0.15, -0.25], [-0.56, -0.25], [-0.56, 0.25]] 
inflation_radius: 0.6
cost_scaling_factor: 1.0
obstacle_layer:
  observation_sources: laser_scan_sensor 
  laser_scan_sensor: {sensor_frame: xv11, data_type: LaserScan, topic: /xv11_scan, marking: true, clearing: true, expected_update_rate: 0.4, inf_is_valid: true}

sonar_layer:
    topics: ["/sonar1", "/sonar2", "/sonar3", "/sonar4", "/sonar5", "/sonar6", "/sonar7", "/sonar8"]
    #topics: ["sonar7", "sonar8"]
    no_readings_timeout: 0.0
    clear_threshold: 0.46
    mark_threshold: 0.98
    clear_on_max_reading: true
